webtalk_init -webtalk_dir C:/Users/quant_sz9uc09/OneDrive/Desktop/EE2026/EE2026/BomberMan.xpr/BomberMan/BomberMan.sim/sim_1/behav/xsim/xsim.dir/sim_flickerBomb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 28 12:16:14 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0997648b6c9b561ca3aa90e340da692e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "30bb2e40db0e44d189e4858c0698a140" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4227026382 -regid "" -xml C:/Users/quant_sz9uc09/OneDrive/Desktop/EE2026/EE2026/BomberMan.xpr/BomberMan/BomberMan.sim/sim_1/behav/xsim/xsim.dir/sim_flickerBomb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/quant_sz9uc09/OneDrive/Desktop/EE2026/EE2026/BomberMan.xpr/BomberMan/BomberMan.sim/sim_1/behav/xsim/xsim.dir/sim_flickerBomb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/quant_sz9uc09/OneDrive/Desktop/EE2026/EE2026/BomberMan.xpr/BomberMan/BomberMan.sim/sim_1/behav/xsim/xsim.dir/sim_flickerBomb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
